---
abstract: 'be like TOBYINK and use these Plack stuffz'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::TOBYINK::Plack
name: Task-BeLike-TOBYINK-Plack
no_index:
  directory:
    - inc
    - xt
requires:
  Gepok: 0
  Plack: 0
  Plack::Middleware::GepokX::ModSSL: 0
  RDF::ACL: 0
  Web::ID: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-BeLike-TOBYINK-Plack
  homepage: https://metacpan.org/release/Task-BeLike-TOBYINK-Plack
  license: http://dev.perl.org/licenses/
version: 2012.155
